# Lightweight gate: pins, license, shell syntax, harness unit tests.
# Full Stage-1 Docker smokes: smoke-stage1.yml (also on pull_request).
name: smoke-syntax

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: make check
        run: make check
